-- COPYRIGHT (C) 2016 PAU CARRÉ CARDONA - ALL RIGHTS RESERVED
-- YOU MAY USE, DISTRIBUTE AND MODIFY THIS CODE UNDER THE
-- TERMS OF THE APACHE LICENSE V2.0 (HTTP://WWW.APACHE.ORG/LICENSES/LICENSE-2.0.TXT).

CREATE TABLE IF NOT EXISTS "BOUNDING_BOX"(
  "FILE_NAME" VARCHAR(255) PRIMARY KEY,
  "TOP" INT NOT NULL,
  "LEFT" INT NOT NULL,
  "BOTTOM" INT NOT NULL,
  "RIGHT" INT NOT NULL,
  "WIDTH" INT NOT NULL,
  "HEIGHT" INT NOT NULL,
  "DATASET" VARCHAR(255) DEFAULT 'UNKNOWN'
);

CREATE TABLE IF NOT EXISTS "SIMILARITY"(
  "REFERENCE" VARCHAR(255),
  "POSITIVE"  VARCHAR(255),
  "NEGATIVE"  VARCHAR(255),
  "DATASET" VARCHAR(255) DEFAULT 'UNKNOWN',
  PRIMARY KEY("REFERENCE", "POSITIVE", "NEGATIVE")
);

CREATE TABLE IF NOT EXISTS "BOUNDING_BOX_Info"(
  "FILE_NAME" VARCHAR(255),
  "TOP" INT NOT NULL,
  "LEFT" INT NOT NULL,
  "BOTTOM" INT NOT NULL,
  "RIGHT" INT NOT NULL,
  "WIDTH" INT NOT NULL,
  "HEIGHT" INT NOT NULL,
  "CLASS" VARCHAR(255),
  "Prob" FLOAT,
  "DATASET" VARCHAR(255) DEFAULT 'UNKNOWN',
  PRIMARY KEY ("FILE_NAME", "TOP", "LEFT", "BOTTOM","RIGHT","CLASS")
);
